name: Pipeline

on:
  push:
    branches: [ deployment ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running Tests
      id: tests
      run: echo Testing Done!!!!

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Heroku
      id: deploy
      run: echo deployment Done!
