name: Pipeline

on:
  push:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the docker image
      run: echo TESTTTTTt YAy!!!!
    - name: Run a multi-line script
      run: |
        echo pull the docker image
        echo test, and deploy flask here


    - step:
      name: Prod Environment
      trigger: manual
    - name: Pull the docker image
      run: echo For Prod Push!!!!
    - name: Run a multi-line script
      run: |
        echo pull the docker image
        echo test, and deploy flask here

