name: Pipeline

on:
  push:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the project
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name : Deploy Step
      run : echo wait a sec deploying in action "${{secrets.HEROKU_USERNAME}}"
      
