name: Pipeline

on:
  push:
    branches: [ deployment ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running Tests
      id: tests
      run: echo Testing Done!.!!!

  build:
    runs-on: ubuntu-latest
    container:
        image: dash33/python-hello-world:latest
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: echo deploy
