name: Pipeline

on:
  push:
    branches: [ deployment ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Running Tests
      id: tests
      run: echo Testing Done!!!!

  deploy:
    container:
        image: dash33/python-hello-world:latest
