name: Pipeline

on:
  push:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Pull the docker image
      id: pull_dockerid
      run: echo TESTTTTTt YAy!!!!
    - name: Run a multi-line script
      id: run_tests
      run: |
        echo pull the docker image
        echo test, and deploy flask here
    - name: Dsds
      id: deploy

