name: Pipeline

on: [push]

jobs:
  build:
    steps:
    - name: Pull the docker image
      run: echo TESTTTTTt YAy!!!!
    - name: Run a multi-line script
      run: |
        echo pull the docker image
        echo test, and deploy flask here
